### ISSUE TITLE
KeyError: 'PROGRAMFILES(X86)' with ST3 on 32bit OS

### ISSUE THREAD

**Issue by debjan** [kemayo/sublime-text-git#307]
This line: https://github.com/kemayo/sublime-text-git/blob/python3/git.py#L120

``` python
...
os.path.join(os.environ["ProgramFiles(x86)"], "Git", "bin"),
...
```

causes error on plugin loading when running on 32bit Windows because such variable does not exist.

Perhaps offending line could be deleted or existing code enriched with bitness detection

**Comment by miguelhughes** [comment]
I get this too... any way to make it work? I also use win32 and sublime text 3...

I've tried installing via package control and also via git, using the appropiate branch:
$ git clone git://github.com/kemayo/sublime-text-git.git Git
$ cd Git
$ git checkout python3

When I open ST3, the commands aren't available on the commant palette.
I get this log on console.:
```
reloading plugin Git.add
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\add.py", line 5, in <module>
    from .git import GitTextCommand, GitWindowCommand, git_root
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 135, in <module>
    GIT = find_git()
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 126, in find_git
    os.path.join(os.environ["ProgramFiles(x86)"], "Git", "bin"),
  File "./os.py", line 676, in __getitem__
KeyError: 'ProgramFiles(x86)'
reloading plugin Git.annotate
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\annotate.py", line 7, in <module>
    from .git import git_root, GitTextCommand
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 135, in <module>
    GIT = find_git()
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 126, in find_git
    os.path.join(os.environ["ProgramFiles(x86)"], "Git", "bin"),
  File "./os.py", line 676, in __getitem__
KeyError: 'ProgramFiles(x86)'
reloading plugin Git.commit
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\commit.py", line 7, in <module>
    from .git import GitTextCommand, GitWindowCommand, plugin_file, view_contents, _make_text_safeish
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 135, in <module>
    GIT = find_git()
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 126, in find_git
    os.path.join(os.environ["ProgramFiles(x86)"], "Git", "bin"),
  File "./os.py", line 676, in __getitem__
KeyError: 'ProgramFiles(x86)'
reloading plugin Git.diff
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\diff.py", line 4, in <module>
    from .git import git_root, GitTextCommand, GitWindowCommand, do_when, goto_xy
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 135, in <module>
    GIT = find_git()
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 126, in find_git
    os.path.join(os.environ["ProgramFiles(x86)"], "Git", "bin"),
  File "./os.py", line 676, in __getitem__
KeyError: 'ProgramFiles(x86)'
reloading plugin Git.flow
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\flow.py", line 2, in <module>
    from .git import GitWindowCommand
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 135, in <module>
    GIT = find_git()
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 126, in find_git
    os.path.join(os.environ["ProgramFiles(x86)"], "Git", "bin"),
  File "./os.py", line 676, in __getitem__
KeyError: 'ProgramFiles(x86)'
reloading plugin Git.git
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 135, in <module>
    GIT = find_git()
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 126, in find_git
    os.path.join(os.environ["ProgramFiles(x86)"], "Git", "bin"),
  File "./os.py", line 676, in __getitem__
KeyError: 'ProgramFiles(x86)'
reloading plugin Git.history
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\history.py", line 6, in <module>
    from .git import GitTextCommand, GitWindowCommand, plugin_file
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 135, in <module>
    GIT = find_git()
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 126, in find_git
    os.path.join(os.environ["ProgramFiles(x86)"], "Git", "bin"),
  File "./os.py", line 676, in __getitem__
KeyError: 'ProgramFiles(x86)'
reloading plugin Git.repo
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\repo.py", line 4, in <module>
    from .git import GitWindowCommand, git_root_exist
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 135, in <module>
    GIT = find_git()
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 126, in find_git
    os.path.join(os.environ["ProgramFiles(x86)"], "Git", "bin"),
  File "./os.py", line 676, in __getitem__
KeyError: 'ProgramFiles(x86)'
reloading plugin Git.stash
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\stash.py", line 1, in <module>
    from .git import GitWindowCommand
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 135, in <module>
    GIT = find_git()
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 126, in find_git
    os.path.join(os.environ["ProgramFiles(x86)"], "Git", "bin"),
  File "./os.py", line 676, in __getitem__
KeyError: 'ProgramFiles(x86)'
reloading plugin Git.status
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\status.py", line 5, in <module>
    from .git import GitWindowCommand, git_root
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 135, in <module>
    GIT = find_git()
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 126, in find_git
    os.path.join(os.environ["ProgramFiles(x86)"], "Git", "bin"),
  File "./os.py", line 676, in __getitem__
KeyError: 'ProgramFiles(x86)'
reloading plugin Git.statusbar
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\statusbar.py", line 5, in <module>
    from .git import GitTextCommand, do_when, are_commands_working
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 135, in <module>
    GIT = find_git()
  File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\Git\git.py", line 126, in find_git
    os.path.join(os.environ["ProgramFiles(x86)"], "Git", "bin"),
  File "./os.py", line 676, in __getitem__
KeyError: 'ProgramFiles(x86)'
```

If you can help that'd be awesome, I'd love to have this plugin on st3..

**Comment by debjan** [comment]
@miguelhughes I dont use this plugin anymore, but as a workaround you can set new environment variable (in Advanced System Settings dialog) named `ProgramFiles(86)` with your current value of `%ProgramFiles% ` variable.

Until someone is willing to change the code to check if `os.environ.get("ProgramFiles(x86)")` is `None` and commit.
