### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 25: ordinal not in range(128)

### ISSUE THREAD

**Issue by nietonfir** [kemayo/sublime-text-git#392]
If I want to write a commit message containing [`…`](http://en.wikipedia.org/wiki/Ellipsis) (e.g. `Fix smthg…`) nothing happens. Instead I get the following exception in the console:

``` python
Exception in thread Thread-1911:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "./git.py", line 123, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 691, in communicate
    return self._communicate(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1222, in _communicate
    bytes_written = os.write(self.stdin.fileno(), chunk)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 25: ordinal not in range(128)
```

That used to work flawlessly (the most recent commit containing ellipsis I could find was from december (`Date:   Sat Dec 13 01:01:05 2014 +0100`)). Could this be related to the fix introduced in #383?
Sublime Version: 2.0.2, Build 2221
OS: OS X 10.9.5 (13F34)

**Comment by blalor** [comment]
Also seeing this problem.

**Comment by nietonfir** [comment]
I'm closing this issue since no one commented for almost two years and the problem doesn't exist in ST3 (at least for me).
