### ISSUE TITLE
commit does not work when comment contais `[` and `]`

### ISSUE THREAD

**Issue by iGusev** [kemayo/sublime-text-git#416]

**Comment by iGusev** [comment]
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 21: ordinal not in range(128)
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 232, in on_close
    callback.on_close(v)
  File "commit in /Users/iGusev/Library/Application Support/Sublime Text 3/Installed Packages/Git.sublime-package", line 153, in on_close
  File "commit in /Users/iGusev/Library/Application Support/Sublime Text 3/Installed Packages/Git.sublime-package", line 126, in message_done
  File "./encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 20: ordinal not in range(128)
```
